export const DOMAIN_RULES = {
    ceza: {
        label: 'Ceza',
        profiles: ['ceza'],
        sources: ['yargitay'],
        suggestedCourt: 'Ceza Dairesi (suc tipine gore 1-12)',
        strictResultMode: true,
        principles: ['supheden sanik yararlanir', 'somut delil', 'ispat'],
        negative: ['hukuk dairesi', '4. hukuk dairesi', 'danistay', 'idare mahkemesi', 'bosanma', 'ise iade'],
        detection: [
            /\b(tck|cmk|iddianame|cumhuriyet bassavciligi|sanik|supheli|mudafii|ceza mahkemesi)\b/i,
            /\b(uyusturucu|yaralama|hirsizlik|dolandiricilik|nitelikli hirsizlik|hukuka aykiri delil|hakaret|cinsel istismar|cinsel saldiri|kasten oldurme|tehdit|yagma|kacakcilik|sahtecilik|trafik guvenligi|rusvet|zimmet|teror)\b/i,
        ],
        defaultVariant: {
            subdomain: 'ceza_genel',
            core: 'Ceza yargilamasinda suc vasfi, ispat ve delillerin birlikte degerlendirilmesi',
            retrieval: ['ceza yargilamasi', 'suc vasfi', 'ispat'],
            support: ['supheden sanik yararlanir', 'somut delil', 'mahkumiyet'],
            primaryBirimCodes: ['C1', 'C4', 'C10', 'C11', 'C12'],
            clauses: [
                '+\"ceza\" +\"suc vasfi\" +\"ispat\"',
                '+\"supheden sanik yararlanir\" +\"beraat\" +\"delil\"',
            ],
        },
        variants: [
            {
                when: /\b(hukuka aykiri delil|arama karari olmadan|telefon incelemesi|dijital delil|cmk 217|el koyma)\b/i,
                subdomain: 'ceza_hukuka_aykiri_delil',
                suggestedCourt: 'Ceza Dairesi (suc tipine bagli)',
                allowEvidenceAsCore: true,
                core: 'Hukuka aykiri elde edilen delilin mahkumiyete esas alinip alinmayacagi',
                retrieval: ['hukuka aykiri delil', 'cmk 217', 'delil yasaklari'],
                support: ['arama karari', 'dislama kurali', 'dijital delil'],
                evidence: ['arama tutanagi', 'telefon incelemesi', 'el koyma'],
                clauses: [
                    '+\"hukuka aykiri delil\" +\"arama\" +\"dislama\"',
                    '+\"CMK 217\" +\"dijital delil\" +\"beraat\"',
                ],
            },
            {
                when: /\b(uyusturucu|uyarici madde|tck 188|tck 191|metamfetamin|kokain|esrar|sentetik kannabinoid)\b/i,
                subdomain: 'ceza_uyusturucu',
                suggestedCourt: '8. Ceza Dairesi, 10. Ceza Dairesi',
                primaryBirimCodes: ['C10'],
                secondaryBirimCodes: ['C8', 'C20'],
                core: 'Uyusturucu madde ticareti ile kullanmak icin bulundurma ayriminin ve ticaret kastinin belirlenmesi',
                retrieval: ['uyusturucu madde ticareti', 'kullanmak icin bulundurma', 'tck 188'],
                support: ['tck 191', 'ticaret kasti', 'kisisel kullanim siniri'],
                evidence: ['paketleme', 'hassas terazi', 'hts kaydi', 'telefon incelemesi', 'ele gecirilen miktar', 'tanik'],
                clauses: [
                    '+\"kullanmak icin bulundurma\" +\"kisisel kullanim siniri\" +\"beraat\"',
                    '+\"uyusturucu madde ticareti\" +\"gorevsizlik\" +\"agir ceza\"',
                    '+\"TCK 188\" +\"TCK 191\" +\"ayrim\"',
                    '+\"kullanma siniri\" +\"ticaret kasti\" +\"ispat\"',
                ],
            },
            {
                when: /\b(kasten oldurme|tck 81|tck 82|tck 83|intihara yonlendirme|kasten yaralama|tck 86|tck 87)\b/i,
                subdomain: 'ceza_kasten_oldurme_yaralama',
                suggestedCourt: '1. Ceza Dairesi',
                primaryBirimCodes: ['C1'],
                core: 'Kasten oldurme ve yaralama sucunda fiilin niteliginin ve agirlastirici hallerin degerlendirilmesi',
                retrieval: ['kasten oldurme', 'kasten yaralama', 'tck 81'],
                support: ['nitelikli hal', 'kasten oldurme', 'kasten yaralama'],
                evidence: ['otopsi', 'adli tip', 'kamera goruntusu', 'tanik'],
                clauses: [
                    '+\"kasten oldurme\" +\"TCK 81\" +\"nitelikli hal\"',
                    '+\"kasten yaralama\" +\"TCK 86\" +\"kasten\"',
                ],
            },
            {
                when: /\b(hirsizlik|tck 141|tck 142|konut dokunulmazligi|gece vakti)\b/i,
                subdomain: 'ceza_hirsizlik',
                suggestedCourt: '2. Ceza Dairesi',
                primaryBirimCodes: ['C2'],
                core: 'Hirsizlik eyleminde nitelikli hal ve tesebbus kosullarinin degerlendirilmesi',
                retrieval: ['hirsizlik', 'tck 141', 'nitelikli hirsizlik'],
                support: ['konut dokunulmazligi', 'gece vakti', 'tesebbus'],
                evidence: ['kamera goruntusu', 'parmak izi', 'dna', 'tanik'],
                clauses: [
                    '+\"hirsizlik\" +\"konut\" +\"gece vakti\"',
                    '+\"nitelikli hirsizlik\" +\"TCK 142\" +\"beraat\"',
                ],
            },
            {
                when: /\b(teror|silahli orgut|anayasayi ihlal|devletin guvenligine karsi|casusluk|malvarligi degerlerini aklama|tck 309|tck 314|tck 282)\b/i,
                subdomain: 'ceza_teror_devlet',
                suggestedCourt: '3. Ceza Dairesi',
                primaryBirimCodes: ['C3'],
                core: 'Teror, orgut ve devletin guvenligine karsi suclarda orgutsel bag, fiil ve kastin degerlendirilmesi',
                retrieval: ['silahli orgut', 'teror', 'tck 314'],
                support: ['anayasayi ihlal', 'devletin guvenligi', 'orgutsel bag'],
                evidence: ['dijital materyal', 'iletisim kaydi', 'tanik', 'el koyma'],
                clauses: [
                    '+\"silahli orgut\" +\"TCK 314\" +\"orgutsel bag\"',
                    '+\"teror\" +\"anayasayi ihlal\" +\"devletin guvenligi\"',
                ],
            },
            {
                when: /\b(hakaret|cumhurbaskanina hakaret|nefret|ayrimcilik|gocmen kacakciligi|insan ticareti|fuhus|gorevi yaptirmamak icin direnme|imar kirliligi)\b/i,
                subdomain: 'ceza_hakaret_kamu_duzeni',
                suggestedCourt: '4. Ceza Dairesi',
                primaryBirimCodes: ['C4'],
                core: 'Hakaret, gocmen kacakciligi ve kamu duzenine iliskin suclarda fiilin tipikliginin degerlendirilmesi',
                retrieval: ['hakaret', 'cumhurbaskanina hakaret', 'gocmen kacakciligi'],
                support: ['alenen', 'onur sayginlik', 'gorevi yaptirmamak icin direnme'],
                evidence: ['sosyal medya paylasimi', 'mesaj', 'tanik', 'kamera goruntusu'],
                clauses: [
                    '+\"hakaret\" +\"onur sayginlik\" +\"alenen\"',
                    '+\"gocmen kacakciligi\" +\"insan ticareti\" +\"delil\"',
                ],
            },
            {
                when: /\b(ihaleye fesat|edimin ifasina fesat|tefecilik|zimmet|irtikap|rusvet|nufuz ticareti|gorevi kotuye kullanma)\b/i,
                subdomain: 'ceza_kamu_idaresi_yolsuzluk',
                suggestedCourt: '5. Ceza Dairesi',
                primaryBirimCodes: ['C5'],
                core: 'Kamu idaresine ve kamu guvenine iliskin yolsuzluk tipi suclarda menfaat ve gorev baginin degerlendirilmesi',
                retrieval: ['rusvet', 'zimmet', 'ihaleye fesat'],
                support: ['kamu gorevlisi', 'menfaat', 'gorev', 'ihale'],
                evidence: ['ihale dosyasi', 'para transferi', 'telefon kaydi', 'tanik'],
                clauses: [
                    '+\"rusvet\" +\"kamu gorevlisi\" +\"menfaat\"',
                    '+\"zimmet\" +\"gorev\" +\"kamu zarari\"',
                    '+\"ihaleye fesat\" +\"ihale\" +\"menfaat\"',
                ],
            },
            {
                when: /\b(tehdit|santaj|yagma|gasp|mala zarar verme|tck 106|tck 107|tck 148|tck 149|tck 151)\b/i,
                subdomain: 'ceza_tehdit_yagma',
                suggestedCourt: '6. Ceza Dairesi',
                primaryBirimCodes: ['C6'],
                core: 'Tehdit, santaj, yagma ve mala zarar verme suclarinda cebir ve tehdit unsurlarinin degerlendirilmesi',
                retrieval: ['tehdit', 'yagma', 'santaj'],
                support: ['cebir', 'korkutma', 'mala zarar'],
                evidence: ['kamera goruntusu', 'telefon kaydi', 'tanik', 'adli rapor'],
                clauses: [
                    '+\"tehdit\" +\"cebir\" +\"korkutma\"',
                    '+\"yagma\" +\"santaj\" +\"mala zarar\"',
                ],
            },
            {
                when: /\b(kacakcilik|akaryakit kacakciligi|sigara kacakciligi|alkol kacakciligi|bankacilik kanunu|evrakta sahtecilik birlikte)\b/i,
                subdomain: 'ceza_kacakcilik_bankacilik',
                suggestedCourt: '7. Ceza Dairesi',
                primaryBirimCodes: ['C7'],
                core: 'Kacakcilik ve bankacilik suclarinda ekonomik deger, esya ve fiil butunlugunun degerlendirilmesi',
                retrieval: ['kacakcilik', 'bankacilik sucu', 'akaryakit kacakciligi'],
                support: ['gumruk', 'esya', 'ithal', 'evrakta sahtecilik'],
                evidence: ['arama tutanagi', 'fatura', 'irsaliye', 'ekspertiz'],
                clauses: [
                    '+\"kacakcilik\" +\"gumruk\" +\"esya\"',
                    '+\"bankacilik\" +\"mevduat\" +\"zimmet\"',
                ],
            },
            {
                when: /\b(iskence|eziyet|kisiyi hurriyetinden yoksun kilma|iftira|6136|ruhsatsiz silah|muhurde sahtecilik|parada sahtecilik|kiymetli damgada sahtecilik)\b/i,
                subdomain: 'ceza_hurriyete_karsi_silah_sahtecilik',
                suggestedCourt: '8. Ceza Dairesi',
                primaryBirimCodes: ['C8'],
                core: 'Hurriyete, kamu guvenine ve silah duzenine karsi suclarda fiilin niteliginin ve kastin degerlendirilmesi',
                retrieval: ['kisiyi hurriyetinden yoksun kilma', '6136', 'iftira'],
                support: ['ruhsatsiz silah', 'parada sahtecilik', 'eziyet'],
                evidence: ['arama tutanagi', 'silah ekspertizi', 'tanik', 'kamera goruntusu'],
                clauses: [
                    '+\"kisiyi hurriyetinden yoksun kilma\" +\"cebir\" +\"tanik\"',
                    '+\"6136\" +\"ruhsatsiz silah\" +\"arama\"',
                ],
            },
            {
                when: /\b(cinsel saldiri|cocuklarin cinsel istismari|resit olmayanla cinsel iliski|cinsel taciz|tck 102|tck 103|tck 104|tck 105)\b/i,
                subdomain: 'ceza_cinsel',
                suggestedCourt: '9. Ceza Dairesi',
                primaryBirimCodes: ['C9'],
                core: 'Cinsel suclarda fail-magdur beyanlari, deliller ve fiilin niteliginin degerlendirilmesi',
                retrieval: ['cinsel saldiri', 'cocuklarin cinsel istismari', 'tck 103'],
                support: ['cinsel taciz', 'riza', 'magdur beyani'],
                evidence: ['adli tip raporu', 'psikolog raporu', 'beyan', 'hts kaydi'],
                clauses: [
                    '+\"cocuklarin cinsel istismari\" +\"TCK 103\" +\"beyan\"',
                    '+\"cinsel saldiri\" +\"TCK 102\" +\"magdur\"',
                ],
            },
            {
                when: /\b(dolandiricilik|tck 157|tck 158|hile|aldatma|guveni kotuye kullanma|resmi belgede sahtecilik|ozel belgede sahtecilik|bilisim sistemine girme|banka karti|kredi karti|ataturk aleyhine)\b/i,
                subdomain: 'ceza_dolandiricilik',
                suggestedCourt: '11. Ceza Dairesi',
                primaryBirimCodes: ['C11'],
                core: 'Dolandiricilik sucunda aldatma unsurunun ve magdur iradesine etkisinin degerlendirilmesi',
                retrieval: ['dolandiricilik', 'resmi belgede sahtecilik', 'tck 157'],
                support: ['hile', 'magdur', 'yaniltma', 'guveni kotuye kullanma', 'belgede sahtecilik', 'bilisim sistemi'],
                evidence: ['banka kaydi', 'para transferi', 'mesaj', 'sozlesme'],
                clauses: [
                    '+\"dolandiricilik\" +\"aldatma\" +\"hile\"',
                    '+\"TCK 157\" +\"magdur\" +\"yaniltma\"',
                    '+\"resmi belgede sahtecilik\" +\"aldatma\" +\"bilisim\"',
                ],
            },
            {
                when: /\b(taksirle oldurme|taksirle yaralama|ozel hayatin gizliligi|haberlesmenin gizliligi|kisisel veriler|trafik guvenligini tehlikeye sokma|mustehcenlik|vuk|vergi usul kanunu|tck 85|tck 89|tck 179)\b/i,
                subdomain: 'ceza_taksir_ozel_hayat_trafik',
                suggestedCourt: '12. Ceza Dairesi',
                primaryBirimCodes: ['C12'],
                core: 'Taksir, ozel hayat, kisisel veri ve trafik suclarinda kusur ile hukuka aykirilik unsurlarinin degerlendirilmesi',
                retrieval: ['taksirle oldurme', 'trafik guvenligini tehlikeye sokma', 'ozel hayatin gizliligi'],
                support: ['kisisel veri', 'haberlesme gizliligi', 'taksirle yaralama', 'vuk'],
                evidence: ['bilirkişi raporu', 'trafik tutanagi', 'kamera goruntusu', 'adli rapor'],
                clauses: [
                    '+\"taksirle oldurme\" +\"kusur\" +\"trafik\"',
                    '+\"ozel hayatin gizliligi\" +\"kisisel veri\" +\"haberlesme\"',
                    '+\"trafik guvenligini tehlikeye sokma\" +\"TCK 179\" +\"kusur\"',
                ],
            },
        ],
    },
    is_hukuku: {
        label: 'Is hukuku',
        profiles: ['is_hukuku', 'hukuk'],
        sources: ['yargitay', 'uyap'],
        suggestedCourt: '9. Hukuk Dairesi',
        strictResultMode: true,
        principles: ['ispat yuku', 'hakli fesih', 'gecerli neden'],
        negative: ['ceza dairesi', 'danistay', 'bosanma', 'icra takibi'],
        detection: [
            /\b(is kanunu|ise iade|gecersiz fesih|kidem tazminati|ihbar tazminati|fazla mesai|mobbing)\b/i,
            /\b(iscilik alacagi|yillik izin ucreti|ucret alacagi|is kazasi)\b/i,
        ],
        defaultVariant: {
            subdomain: 'is_hukuku_genel',
            core: 'Is iliskisinden dogan fesih, alacak ve ispat sorunlarinin degerlendirilmesi',
            retrieval: ['is hukuku', 'isci alacagi', 'ispat yuku'],
            support: ['hakli fesih', 'ucret', 'tazminat'],
            primaryBirimCodes: ['H9'],
            clauses: [
                '+\"ise iade\" +\"gecersiz fesih\" +\"ispat yuku\"',
                '+\"kidem tazminati\" +\"hakli fesih\" +\"ispat\"',
            ],
        },
        variants: [
            {
                when: /\b(ise iade|gecersiz fesih|is guvencesi|is k\.?\s*18)\b/i,
                subdomain: 'is_hukuku_ise_iade',
                core: 'Ise iade davasinda feshin gecerli nedene dayanip dayanmadigi ve ispat yuku',
                retrieval: ['ise iade', 'gecersiz fesih', 'is k. 18'],
                support: ['ispat yuku', 'is guvencesi', 'gecerli neden'],
                suggestedCourt: '9. Hukuk Dairesi',
                primaryBirimCodes: ['H9'],
                clauses: [
                    '+\"ise iade\" +\"gecersiz fesih\" +\"ispat yuku\"',
                    '+\"gecersiz fesih\" +\"gecerli neden\" +\"ise iade\"',
                ],
            },
            {
                when: /\b(hizmet tespiti|sigortalilik tespiti|sgk|5510|506 sayili|prim bildirimi|calisma olgusu)\b/i,
                subdomain: 'is_hukuku_hizmet_tespiti',
                core: 'Hizmet tespiti ve sigortalilik uyusmazliginda calisma olgusu ile SGK kayitlarinin degerlendirilmesi',
                retrieval: ['hizmet tespiti', 'sigortalilik tespiti', '5510'],
                support: ['sgk', 'sigortalilik', 'prim', 'calisma olgusu'],
                suggestedCourt: '10. Hukuk Dairesi',
                primaryBirimCodes: ['H10'],
                must: ['hizmet tespiti', 'sigortalilik tespiti'],
                strictMatchMode: 'must_support',
                clauses: [
                    '+\"hizmet tespiti\" +\"sgk\" +\"sigortalilik\"',
                    '+\"5510\" +\"sigortalilik tespiti\" +\"calisma olgusu\"',
                ],
            },
            {
                when: /\b(is kazasi|meslek hastaligi|surekli is goremezlik|sgk geliri|rucu)\b/i,
                subdomain: 'is_hukuku_is_kazasi_sgk',
                core: 'Is kazasi ve meslek hastaligi ekseninde SGK ve tazminat uyusmazliklarinin degerlendirilmesi',
                retrieval: ['is kazasi', 'meslek hastaligi', 'sgk rucu'],
                support: ['surekli is goremezlik', 'sgk geliri', 'kusur', 'rucu'],
                suggestedCourt: '10. Hukuk Dairesi',
                primaryBirimCodes: ['H10'],
                must: ['is kazasi', 'meslek hastaligi'],
                strictMatchMode: 'must_support',
                clauses: [
                    '+\"is kazasi\" +\"sgk\" +\"kusur\"',
                    '+\"meslek hastaligi\" +\"surekli is goremezlik\" +\"rucu\"',
                ],
            },
            {
                when: /\b(fazla mesai|fazla calisma|puantaj|bordro|is k\.?\s*41)\b/i,
                subdomain: 'is_hukuku_fazla_mesai',
                core: 'Fazla mesai alacaginda bordro, puantaj ve tanik anlatimlarinin degerlendirilmesi',
                retrieval: ['fazla mesai', 'fazla calisma ucreti', 'bordro ihtirazi kayit', 'is k. 41'],
                support: ['bordro', 'puantaj', 'ucret hesap pusulasi', 'ispat', 'devam cizelgesi', 'ise giris cikis kayitlari', 'serbest zaman', 'hafta tatili', 'iscinin onayi'],
                evidence: ['bordro', 'puantaj kaydi', 'ucret hesap pusulasi', 'devam cizelgesi', 'ise giris cikis kayitlari', 'elektronik ortam kayitlari'],
                suggestedCourt: '9. Hukuk Dairesi',
                primaryBirimCodes: ['H9'],
                must: ['fazla mesai', 'fazla calisma', 'fazla surelerle calisma'],
                deny: ['sgk', '5510', '506', '5434', 'bag-kur', 'hizmet tespiti', 'is kazasi', 'meslek hastaligi', 'rucu', 'issizlik odenegi'],
                strictMatchMode: 'must_support',
                clauses: [
                    '+\"fazla mesai\" +\"puantaj\" +\"ispat\"',
                    '+\"fazla calisma\" +\"bordro\" +\"ucret hesap pusulasi\"',
                    '+\"fazla surelerle calisma\" +\"devam cizelgesi\" +\"ise giris cikis kayitlari\"',
                ],
            },
            {
                when: /\b(kidem tazminati|ihbar tazminati|hakli fesih|askerlik nedeniyle fesih)\b/i,
                subdomain: 'is_hukuku_fesih_alacak',
                core: 'Kidem ve ihbar tazminati taleplerinde feshin hakli nedenlere dayanip dayanmadigi',
                retrieval: ['kidem tazminati', 'hakli fesih', 'is k. 14'],
                support: ['ihbar tazminati', 'askerlik nedeniyle fesih', 'bildirim suresi'],
                suggestedCourt: '9. Hukuk Dairesi',
                primaryBirimCodes: ['H9'],
                clauses: [
                    '+\"kidem tazminati\" +\"hakli fesih\" +\"ispat\"',
                    '+\"ihbar tazminati\" +\"haksiz fesih\" +\"bildirim suresi\"',
                ],
            },
            {
                when: /\b(mobbing|psikolojik taciz)\b/i,
                subdomain: 'is_hukuku_mobbing',
                core: 'Mobbing iddiasinda psikolojik baskinin surekliligi ve is iliskisine etkisi',
                retrieval: ['mobbing', 'psikolojik taciz', 'hakli fesih'],
                support: ['kisilik haklari', 'manevi tazminat', 'ispat'],
                suggestedCourt: '9. Hukuk Dairesi',
                primaryBirimCodes: ['H9'],
                clauses: [
                    '+\"mobbing\" +\"psikolojik baski\" +\"hakli fesih\"',
                    '+\"mobbing\" +\"manevi tazminat\" +\"ispat\"',
                ],
            },
        ],
    },
    aile: {
        label: 'Aile hukuku',
        profiles: ['aile', 'hukuk'],
        sources: ['yargitay', 'uyap'],
        suggestedCourt: '2. Hukuk Dairesi',
        strictResultMode: true,
        principles: ['cocugun ustun yarari', 'evlilik birliginin temelinden sarsilmasi', 'hakkaniyet'],
        negative: ['ceza dairesi', 'danistay', 'idare mahkemesi', 'icra takibi'],
        detection: [
            /\b(bosanma|tmk 166|velayet|nafaka|aile konutu|mal rejimi|ziynet|soybagi)\b/i,
            /\b(6284|uzaklastirma|koruma tedbiri|babalik davasi|kisisel iliski)\b/i,
        ],
        defaultVariant: {
            subdomain: 'aile_genel',
            core: 'Aile hukuku uyusmazliginda bosanma, velayet, nafaka ve mal rejimi sorunlarinin degerlendirilmesi',
            retrieval: ['bosanma', 'velayet', 'nafaka'],
            support: ['mal rejimi', 'aile konutu', 'kisisel iliski'],
            suggestedCourt: '2. Hukuk Dairesi',
            primaryBirimCodes: ['H2'],
            routingMode: 'hard_primary',
            clauses: [
                '+\"bosanma\" +\"evlilik birligi\" +\"cekilmezlik\"',
                '+\"velayet\" +\"cocugun ustun yarari\" +\"degistirilmesi\"',
            ],
        },
        variants: [
            {
                when: /\b(bosanma|tmk 166|sadakatsizlik|ziynet)\b/i,
                subdomain: 'aile_bosanma',
                core: 'Bosanma davasinda kusur, cekilmezlik ve evlilik birliginin temelinden sarsilmasi',
                retrieval: ['bosanma', 'tmk 166', 'evlilik birliginin temelinden sarsilmasi'],
                support: ['kusur', 'maddi tazminat', 'manevi tazminat', 'ziynet esyasi'],
                suggestedCourt: '2. Hukuk Dairesi',
                primaryBirimCodes: ['H2'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"bosanma\" +\"evlilik birligi\" +\"cekilmezlik\"',
                    '+\"ziynet esyasi\" +\"iade\" +\"bosanma\"',
                ],
            },
            {
                when: /\b(velayet|nafaka|kisisel iliski|tmk 182)\b/i,
                subdomain: 'aile_velayet_nafaka',
                core: 'Velayet ve nafaka uyusmazliginda cocugun ustun yarari ile ihtiyac olcusu',
                retrieval: ['velayet', 'cocugun ustun yarari', 'tmk 182'],
                support: ['nafaka', 'kisisel iliski', 'artirim'],
                suggestedCourt: '2. Hukuk Dairesi',
                primaryBirimCodes: ['H2'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"velayet\" +\"cocugun ustun yarari\" +\"degistirilmesi\"',
                    '+\"nafaka\" +\"istirak\" +\"artirim\"',
                ],
            },
            {
                when: /\b(6284|uzaklastirma|koruma tedbiri|zorlama hapsi)\b/i,
                subdomain: 'aile_6284',
                core: '6284 sayili Kanun kapsaminda koruyucu tedbir ve uzaklastirma ihlali',
                retrieval: ['6284 sayili kanun', 'koruyucu tedbir', 'uzaklastirma'],
                support: ['ihlal', 'zorlama hapsi', 'tedbir suresi'],
                evidence: ['tedbir karari', 'polis tutanagi', 'adli tip raporu'],
                suggestedCourt: '2. Hukuk Dairesi',
                primaryBirimCodes: ['H2'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"6284\" +\"uzaklastirma\" +\"ihlal\"',
                    '+\"koruyucu tedbir\" +\"zorlama hapsi\" +\"6284\"',
                ],
            },
            {
                when: /\b(soybagi|babalik|dna)\b/i,
                subdomain: 'aile_soybagi',
                core: 'Soybagi ve babalik davasinda DNA delilinin etkisi',
                retrieval: ['soybagi', 'babalik davasi', 'tmk 301'],
                support: ['dna raporu', 'nufus kaydi', 'hak dusurucu sure'],
                suggestedCourt: '2. Hukuk Dairesi',
                primaryBirimCodes: ['H2'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"soybagi\" +\"DNA\" +\"babalik\"',
                    '+\"TMK 301\" +\"DNA raporu\" +\"babalik\"',
                ],
            },
        ],
    },
    icra: {
        label: 'Icra hukuku',
        profiles: ['icra', 'hukuk'],
        sources: ['yargitay', 'uyap'],
        suggestedCourt: '11. Hukuk Dairesi, 6. Hukuk Dairesi',
        strictResultMode: true,
        principles: ['itiraz suresi', 'borcsuzluk', 'icra inkar tazminati'],
        negative: ['ceza dairesi', 'danistay', 'bosanma', 'idare mahkemesi'],
        detection: [
            /\b(iik|icra|itirazin iptali|menfi tespit|haciz|kambiyo|ihalenin feshi)\b/i,
            /\b(odeme emri|haczedilemezlik|ipotegin paraya cevrilmesi|konkordato)\b/i,
        ],
        defaultVariant: {
            subdomain: 'icra_prosedur',
            core: 'Icra hukukunda takip, icra mahkemesi sikayeti, haciz ve satis sureclerinin degerlendirilmesi',
            retrieval: ['icra mahkemesi', 'sikayet', 'iik 16'],
            support: ['itirazin kaldirilmasi', 'haciz', 'sure'],
            suggestedCourt: '12. Hukuk Dairesi',
            primaryBirimCodes: ['H12'],
            routingMode: 'hard_primary',
            clauses: [
                '+\"icra mahkemesi\" +\"sikayet\" +\"IIK 16\"',
                '+\"itirazin kaldirilmasi\" +\"odeme emri\" +\"icra\"',
            ],
        },
        variants: [
            {
                when: /\b(cari hesap|ticari defter|fatura|mutabakat|hesap ekstresi|bakiye|ticari alacak)\b/i,
                subdomain: 'icra_ticari_itirazin_iptali',
                core: 'Tacirler arasi cari hesap ve ticari alacak uyusmazliginda itirazin iptali ile likit alacagin ispati',
                retrieval: ['itirazin iptali', 'iik 67', 'ticari alacak'],
                support: ['cari hesap', 'ticari defter', 'fatura', 'mutabakat'],
                negative: ['nafaka', 'velayet', 'kisisel iliski', 'aile konutu', 'cocuk', 'es', 'bosanma'],
                suggestedCourt: '11. Hukuk Dairesi',
                primaryBirimCodes: ['H11'],
                secondaryBirimCodes: ['H19'],
                routingMode: 'primary_secondary',
                clauses: [
                    'itirazin iptali cari hesap alacagi icra inkar tazminati',
                    'menfi tespit istirdat icra takibi',
                    'IIK 67 itirazin iptali',
                    'itirazin iptali cari hesap iik 67',
                    'cari hesap ticari defter icra inkar tazminati',
                    'mutabakat cari hesap alacak likit',
                ],
            },
            {
                when: /\b(itirazin iptali|iik 67|icra inkar tazminati)\b/i,
                subdomain: 'icra_itirazin_iptali',
                core: 'Itirazin iptali davasinda alacagin ispat ve icra inkar tazminati',
                retrieval: ['itirazin iptali', 'iik 67', 'icra inkar tazminati'],
                support: ['alacagin ispat', 'likit alacak', 'borca itiraz'],
                suggestedCourt: '11. Hukuk Dairesi, 19. Hukuk Dairesi',
                primaryBirimCodes: ['H11'],
                secondaryBirimCodes: ['H19'],
                routingMode: 'primary_secondary',
                clauses: [
                    'itirazin iptali icra inkar tazminati iik 67',
                    'iik 67 alacagin ispat likit alacak borca itiraz',
                    'itirazin iptali alacak ispat icra takibi',
                ],
            },
            {
                when: /\b(itirazin kaldirilmasi|iik 68|iik 68\/a|icra mahkemesi|sikayet|odeme emrine itiraz)\b/i,
                subdomain: 'icra_itirazin_kaldirilmasi_sikayet',
                core: 'Icra mahkemesinde itirazin kaldirilmasi ve sikayet yolunda takip usulunun denetlenmesi',
                retrieval: ['icra mahkemesi', 'itirazin kaldirilmasi', 'iik 68'],
                support: ['sikayet', 'odeme emri', 'iik 16'],
                suggestedCourt: '12. Hukuk Dairesi',
                primaryBirimCodes: ['H12'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"icra mahkemesi\" +\"itirazin kaldirilmasi\" +\"IIK 68\"',
                    '+\"sikayet\" +\"odeme emri\" +\"icra\"',
                ],
            },
            {
                when: /\b(menfi tespit|istirdat|iik 72|borcsuzluk)\b/i,
                subdomain: 'icra_menfi_tespit',
                core: 'Menfi tespit veya istirdat davasinda borcsuzluk ve takip iliskisi',
                retrieval: ['menfi tespit davasi', 'borcsuzluk', 'iik 72'],
                support: ['istirdat davasi', 'takip oncesi', 'takip sonrasi'],
                suggestedCourt: '11. Hukuk Dairesi, 19. Hukuk Dairesi',
                primaryBirimCodes: ['H11'],
                secondaryBirimCodes: ['H19'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"menfi tespit\" +\"takip oncesi\" +\"IIK 72\"',
                    '+\"istirdat davasi\" +\"borcsuzluk\" +\"IIK 72\"',
                ],
            },
            {
                when: /\b(haciz|haczedilemezlik|maas haczi|iik 82)\b/i,
                subdomain: 'icra_haciz',
                core: 'Haciz ve haczedilemezlik uyusmazliginda takip sinirlari',
                retrieval: ['haciz', 'haczedilemezlik', 'iik 82'],
                support: ['maas haczi', 'dortte bir', 'itiraz suresi'],
                suggestedCourt: '12. Hukuk Dairesi',
                primaryBirimCodes: ['H12'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"haciz\" +\"haczedilemezlik\" +\"IIK 82\"',
                    '+\"maas haczi\" +\"sinir\" +\"dortte bir\"',
                ],
            },
            {
                when: /\b(kambiyo|bono|cek|imzaya itiraz)\b/i,
                subdomain: 'icra_kambiyo',
                core: 'Kambiyo takibinde itiraz suresi ve imza incelemesi',
                retrieval: ['kambiyo senetleri', 'bono', 'itiraz suresi'],
                support: ['cek', 'imzaya itiraz', '5 gun'],
                suggestedCourt: '12. Hukuk Dairesi',
                primaryBirimCodes: ['H12'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"kambiyo\" +\"bono\" +\"itiraz suresi\"',
                    '+\"imzaya itiraz\" +\"kambiyo\" +\"inceleme\"',
                ],
            },
            {
                when: /\b(ihalenin feshi|ipotegin paraya cevrilmesi|artirma|kiymet takdiri)\b/i,
                subdomain: 'icra_ihale',
                core: 'Ihalenin feshi ve ipotegin paraya cevrilmesinde satis usulunun denetlenmesi',
                retrieval: ['ihalenin feshi', 'artirma', 'kiymet takdiri'],
                support: ['ipotegin paraya cevrilmesi', '7 gun', 'ihale tutanagi'],
                suggestedCourt: '12. Hukuk Dairesi',
                primaryBirimCodes: ['H12'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"ihalenin feshi\" +\"artirma\" +\"kiymet takdiri\"',
                    '+\"ipotegin paraya cevrilmesi\" +\"ihale\" +\"fesih\"',
                ],
            },
        ],
    },
    borclar: {
        label: 'Borclar hukuku',
        profiles: ['hukuk'],
        sources: ['yargitay'],
        suggestedCourt: '3. Hukuk Dairesi, 4. Hukuk Dairesi, 6. Hukuk Dairesi, 11. Hukuk Dairesi',
        principles: ['ispat yuku', 'durustluk kurali', 'zamanaasimi'],
        negative: ['ceza dairesi', 'danistay', 'idare mahkemesi', 'tck'],
        detection: [
            /\b(tbk|sozlesmeye aykirilik|haksiz fiil|sebepsiz zenginlesme|vekalet|eser sozlesmesi)\b/i,
            /\b(kira sozlesmesi|kefalet|maddi tazminat|manevi tazminat)\b/i,
        ],
        defaultVariant: {
            subdomain: 'borclar_genel',
            core: 'Borclar hukukunda sozlesme, tazminat ve ispat sorunlarinin degerlendirilmesi',
            retrieval: ['sozlesmeye aykirilik', 'tazminat', 'tbk 112'],
            support: ['ispat yuku', 'durustluk kurali', 'zamanaasimi'],
            suggestedCourt: '3. Hukuk Dairesi',
            primaryBirimCodes: ['H3'],
            routingMode: 'hard_primary',
            clauses: [
                '+\"sozlesme feshi\" +\"tazminat\" +\"muspet zarar\"',
                '+\"haksiz fiil\" +\"kusur\" +\"nedensellik bagi\"',
            ],
        },
        variants: [
            {
                when: /\b(haksiz fiil|tbk 49|manevi tazminat|nedensellik|kusur)\b/i,
                subdomain: 'borclar_haksiz_fiil',
                core: 'Haksiz fiil sorumlulugunda kusur, zarar ve nedensellik bagi',
                retrieval: ['haksiz fiil', 'maddi tazminat', 'tbk 49'],
                support: ['kusur', 'nedensellik bagi', 'manevi tazminat'],
                suggestedCourt: '4. Hukuk Dairesi',
                primaryBirimCodes: ['H4'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"haksiz fiil\" +\"kusur\" +\"nedensellik bagi\"',
                    '+\"manevi tazminat\" +\"kisilik hakki\" +\"ihlal\"',
                ],
            },
            {
                when: /\b(kira|tbk 347|tbk 350|tahliye|kira artisi)\b/i,
                subdomain: 'borclar_kira',
                core: 'Kira iliskisinde tahliye, ihtiyac ve kira artis kosullari',
                retrieval: ['kira sozlesmesi', 'tahliye', 'tbk 347'],
                support: ['ihtiyac', 'tbk 350', 'tufe', 'icra mahkemesi', 'itirazin kaldirilmasi', 'finansal kiralama'],
                suggestedCourt: '3. Hukuk Dairesi, 12. Hukuk Dairesi, 11. Hukuk Dairesi',
                primaryBirimCodes: ['H3'],
                secondaryBirimCodes: ['H12', 'H11'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"kira tahliye\" +\"ihtiyac\" +\"TBK 350\"',
                    '+\"kira artisi\" +\"TUFE\" +\"TBK 344\"',
                ],
            },
            {
                when: /\b(vekalet|ozen borcu|eser sozlesmesi|ayipli is|tbk 474)\b/i,
                subdomain: 'borclar_vekalet_eser',
                core: 'Vekalet ve eser sozlesmesinde ozen borcu ile ayipli is sorumlulugu',
                retrieval: ['vekalet sozlesmesi', 'eser sozlesmesi', 'tbk 474'],
                support: ['ozen yukumlulugu', 'ayipli is', 'onarim'],
                suggestedCourt: '6. Hukuk Dairesi',
                primaryBirimCodes: ['H6'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"vekalet\" +\"ozen borcu\" +\"tazminat\"',
                    '+\"eser sozlesmesi\" +\"ayipli is\" +\"onarim\"',
                ],
            },
        ],
    },
    gayrimenkul: {
        label: 'Gayrimenkul hukuku',
        profiles: ['gayrimenkul', 'hukuk'],
        sources: ['yargitay'],
        suggestedCourt: '1. Hukuk Dairesi, 7. Hukuk Dairesi, 5. Hukuk Dairesi, 6. Hukuk Dairesi',
        strictResultMode: true,
        principles: ['mulkiyet hakki', 'tapu guveni', 'ispat yuku'],
        negative: ['ceza dairesi', 'danistay', 'vergi dava dairesi', 'tck'],
        detection: [
            /\b(tapu|tescil|ecrimisil|elatmanin onlenmesi|muris muvazaasi|ortakligin giderilmesi)\b/i,
            /\b(kat karsiligi insaat|kat mulkiyeti|aidat|tasinmaz satis vaadi|kamulastirmasiz el atma)\b/i,
        ],
        defaultVariant: {
            subdomain: 'gayrimenkul_genel',
            core: 'Gayrimenkul uyusmazliginda tapu, paydaslik ve mulkiyet iliskilerinin degerlendirilmesi',
            retrieval: ['tapu iptali ve tescil', 'elatmanin onlenmesi', 'ecrimisil'],
            support: ['mulkiyet hakki', 'ispat yuku', 'tapu kaydi', 'ortakligin giderilmesi'],
            clauses: [
                '+\"tapu iptali\" +\"tescil\" +\"tasinmaz\"',
                '+\"elatmanin onlenmesi\" +\"ecrimisil\" +\"mulkiyet\"',
            ],
        },
        variants: [
            {
                when: /\b(tapu iptali|tescil|yolsuz tescil|muris muvazaasi)\b/i,
                subdomain: 'gayrimenkul_tapu',
                core: 'Tapu iptali ve tescil davalarinda yolsuz tescil, muvazaa ve mulkiyet iliskisinin degerlendirilmesi',
                retrieval: ['tapu iptali ve tescil', 'muris muvazaasi', 'yolsuz tescil'],
                support: ['miras birakanin gercek iradesi', 'muvazaali devir', 'sakli pay', 'bedelsiz devir'],
                evidence: ['tapu kaydi', 'banka hareketi', 'tanik'],
                suggestedCourt: '1. Hukuk Dairesi',
                primaryBirimCodes: ['H1'],
                routingMode: 'hard_primary',
                must: ['tapu iptali', 'tescil', 'muris muvazaasi'],
                deny: ['kira', 'ecrimisil', 'kat karsiligi insaat', 'ortakligin giderilmesi'],
                strictMatchMode: 'must_support',
                clauses: [
                    '+\"muris muvazaasi\" +\"tapu iptali\" +\"tescil\"',
                    '+\"miras birakanin gercek iradesi\" +\"muvazaali devir\" +\"tapu\"',
                    '+\"yolsuz tescil\" +\"tapu kaydi\" +\"mulkiyet\"',
                ],
            },
            {
                when: /\b(ortakligin giderilmesi|izalei suyu|paydas|elbirligi)\b/i,
                subdomain: 'gayrimenkul_ortaklik',
                core: 'Ortakligin giderilmesi davalarinda paydaslik ve satis veya aynen taksim ihtimallerinin degerlendirilmesi',
                retrieval: ['ortakligin giderilmesi', 'izalei suyu', 'payli mulkiyet'],
                support: ['aynen taksim', 'satis suretiyle giderme', 'elbirligi mulkiyeti', 'kamulastirmasiz el atma'],
                suggestedCourt: '7. Hukuk Dairesi, 5. Hukuk Dairesi',
                primaryBirimCodes: ['H7'],
                secondaryBirimCodes: ['H5'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"ortakligin giderilmesi\" +\"aynen taksim\" +\"payli mulkiyet\"',
                    '+\"izalei suyu\" +\"satis\" +\"paydas\"',
                ],
            },
            {
                when: /\b(elatmanin onlenmesi|ecrimisil|fuzuli isgal)\b/i,
                subdomain: 'gayrimenkul_ecrimisil',
                core: 'Elatmanin onlenmesi ve ecrimisil taleplerinde haksiz isgalin ve gelir kaybinin degerlendirilmesi',
                retrieval: ['elatmanin onlenmesi', 'ecrimisil', 'fuzuli isgal'],
                support: ['haksiz isgal tazminati', 'mulkiyet hakki', 'tasinmaz kullanimi', 'kamulastirmasiz el atma'],
                suggestedCourt: '7. Hukuk Dairesi, 5. Hukuk Dairesi',
                primaryBirimCodes: ['H7'],
                secondaryBirimCodes: ['H5'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"elatmanin onlenmesi\" +\"ecrimisil\" +\"fuzuli isgal\"',
                    '+\"haksiz isgal\" +\"tasinmaz\" +\"ecrimisil\"',
                ],
            },
            {
                when: /\b(kat karsiligi insaat|tasinmaz satis vaadi|kat mulkiyeti|aidat)\b/i,
                subdomain: 'gayrimenkul_insaat_kat',
                core: 'Kat karsiligi insaat, tasinmaz satis vaadi ve kat mulkiyeti iliskilerinde sozlesme ve yonetim sorunlarinin degerlendirilmesi',
                retrieval: ['kat karsiligi insaat', 'tasinmaz satis vaadi', 'kat mulkiyeti'],
                support: ['aidat borcu', 'yonetim plani', 'bagimsiz bolum devri'],
                suggestedCourt: '6. Hukuk Dairesi',
                primaryBirimCodes: ['H6'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"kat karsiligi insaat\" +\"arsa payi\" +\"bagimsiz bolum\"',
                    '+\"tasinmaz satis vaadi\" +\"tapuya serh\" +\"tescil\"',
                ],
            },
        ],
    },
    ticaret: {
        label: 'Ticaret hukuku',
        profiles: ['ticaret', 'hukuk'],
        sources: ['yargitay'],
        suggestedCourt: '11. Hukuk Dairesi, 6. Hukuk Dairesi',
        strictResultMode: true,
        principles: ['ticari defter', 'yetki', 'ticari faiz'],
        negative: ['ceza dairesi', 'danistay', 'bosanma'],
        detection: [
            /\b(ttk|anonim sirket|limited sirket|genel kurul|ortaklar kurulu|haksiz rekabet|marka)\b/i,
            /\b(cari hesap|cek bedeli|konkordato|iflas|acente|denklestirme)\b/i,
        ],
        defaultVariant: {
            subdomain: 'ticaret_genel',
            core: 'Ticaret hukukunda sirket, ticari alacak ve kambiyo uyusmazliklari',
            retrieval: ['ticari alacak', 'ttk', 'sirket uyusmazligi'],
            support: ['ticari defter', 'faiz', 'yetki'],
            suggestedCourt: '11. Hukuk Dairesi',
            primaryBirimCodes: ['H11'],
            routingMode: 'hard_primary',
            clauses: [
                '+\"anonim sirket\" +\"genel kurul karari\" +\"iptal\"',
                '+\"ticari alacak\" +\"cari hesap\" +\"faiz\"',
            ],
        },
        variants: [
            {
                when: /\b(marka|iltibas|tescilsiz kullanim|marka tecavuzu|hukumsuzluk)\b/i,
                subdomain: 'ticaret_marka_iltibas',
                core: 'Marka hakkina tecavuz, iltibas ve haksiz rekabet uyusmazliginda tescil ve koruma kapsamining degerlendirilmesi',
                retrieval: ['marka hakki', 'iltibas', 'haksiz rekabet'],
                support: ['tescil', 'hukumsuzluk', 'tecavuz', 'karistirilma ihtimali', 'ayirt edilemeyecek benzerlik', 'tescilli marka', 'unvan', 'logo', 'alan adi', 'e-ticaret', 'internet satisi', 'sinif benzerligi'],
                suggestedCourt: '11. Hukuk Dairesi',
                primaryBirimCodes: ['H11'],
                must: ['marka'],
                deny: ['tapu', 'muris muvazaasi', 'icra', 'kambiyo', 'cari hesap', 'sigorta'],
                strictMatchMode: 'must_support',
                clauses: [
                    '+\"marka\" +\"karistirilma ihtimali\" +\"haksiz rekabet\"',
                    '+\"marka hakkina tecavuz\" +\"tescilli marka\" +\"iltibas\"',
                    '+\"marka\" +\"ayirt edilemeyecek benzerlik\" +\"tescil\"',
                    'tescilli marka haksiz rekabet',
                ],
            },
            {
                when: /\b(anonim sirket|genel kurul|ttk 409|ttk 445|ttk 446|cagri usulsuzlugu)\b/i,
                subdomain: 'ticaret_genel_kurul',
                core: 'Anonim sirket genel kurul kararlarinin iptali ve usul denetimi',
                retrieval: ['genel kurul kararinin iptali', 'genel kurul', 'ttk 445', 'ttk 446', 'anonim sirket'],
                support: ['anonim sirket', 'pay sahipligi', 'cagri usulsuzlugu', 'bilgi alma hakki', 'hazirun cetveli', 'butlan', 'yokluk', 'toplanti nisabi', 'gundem', 'karar defteri', 'toplanti ve muzakere defteri', 'pay defteri', 'yonetim kurulu'],
                suggestedCourt: '11. Hukuk Dairesi',
                primaryBirimCodes: ['H11'],
                must: ['genel kurul'],
                deny: ['icra', 'takip', 'kambiyo', 'marka', 'sigorta', 'konkordato', 'tapu', 'muris muvazaasi', 'tescil', 'cari hesap', 'dernek', 'vakif', 'kooperatif', 'ek tasfiye', 'cekismesiz yargi', 'asliye hukuk mahkemesi', 'tacir sifati'],
                strictMatchMode: 'must_support',
                clauses: [
                    '+\"genel kurul karari\" +\"iptal\" +\"TTK 445\"',
                    '+\"genel kurul\" +\"cagri usulsuzlugu\" +\"pay sahipligi\"',
                    '+\"genel kurul\" +\"butlan\" +\"TTK 446\"',
                    '+\"anonim sirket\" +\"genel kurul\" +\"pay sahipligi\"',
                    '+\"genel kurul\" +\"hazirun cetveli\" +\"gundem\"',
                ],
            },
            {
                when: /\b(limited sirket|ortaklar kurulu|mudur sorumlulugu)\b/i,
                subdomain: 'ticaret_limited',
                core: 'Limited sirkette ortaklar kurulu ve mudur sorumlulugu',
                retrieval: ['limited sirket', 'ortaklar kurulu', 'mudur sorumlulugu'],
                support: ['ttk 573', 'sorumluluk', 'iptal'],
                suggestedCourt: '11. Hukuk Dairesi',
                primaryBirimCodes: ['H11'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"limited sirket\" +\"ortaklar kurulu\" +\"mudur sorumlulugu\"',
                    '+\"TTK 573\" +\"limited sirket\" +\"ortaklik\"',
                ],
            },
            {
                when: /\b(cari hesap|cek bedeli|bono|kambiyo)\b/i,
                subdomain: 'ticaret_alacak_kambiyo',
                core: 'Ticari alacak ve kambiyo iliskisinde belge, faiz ve defter degerlendirmesi',
                retrieval: ['ticari alacak', 'cari hesap', 'cek bedeli'],
                support: ['kambiyo senedi', 'faiz', 'ticari defter'],
                suggestedCourt: '11. Hukuk Dairesi, 19. Hukuk Dairesi',
                primaryBirimCodes: ['H11'],
                secondaryBirimCodes: ['H19'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"ticari alacak\" +\"cari hesap\" +\"faiz\"',
                    '+\"cek\" +\"kambiyo\" +\"itiraz\"',
                ],
            },
            {
                when: /\b(konkordato|iflas|iik 285|tasdik|masaya dahil)\b/i,
                subdomain: 'ticaret_konkordato_iflas',
                core: 'Konkordato ve iflas surecinde alacakli durumu ve tasdik kosullari',
                retrieval: ['konkordato', 'alacakli', 'iik 285'],
                support: ['iflas', 'tasdik', 'sira cetveli'],
                suggestedCourt: '6. Hukuk Dairesi, 23. Hukuk Dairesi',
                primaryBirimCodes: ['H6'],
                secondaryBirimCodes: ['H23'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"konkordato\" +\"alacakli\" +\"tasdik\"',
                    '+\"iflas\" +\"masaya dahil\" +\"sira cetveli\"',
                ],
            },
        ],
    },
    idare: {
        label: 'Idare hukuku',
        profiles: ['idare'],
        sources: ['danistay', 'uyap'],
        suggestedCourt: '6. Daire, 14. Daire, 13. Daire',
        strictResultMode: true,
        principles: ['hukuka aykirilik', 'orantililik', 'hukuki guvenlik'],
        negative: ['ceza dairesi', 'hukuk dairesi', 'bosanma', 'ise iade'],
        detection: [
            /\b(idari islem|iptal davasi|tam yargi|imar para cezasi|ruhsat iptali|kamulastirma)\b/i,
            /\b(disiplin cezasi|belediye|encumen karari|kamu ihale|ced|cevre izni)\b/i,
        ],
        defaultVariant: {
            subdomain: 'idare_genel',
            core: 'Idare hukukunda islem, eylem ve iptal denetiminin degerlendirilmesi',
            retrieval: ['idari islem iptali', 'hukuka aykirilik', 'iptal davasi'],
            support: ['orantililik', 'hukuki guvenlik', 'takdir yetkisi'],
            sourcePolicy: 'danistay',
            routingMode: 'source_first',
            clauses: [
                '+\"idari islem\" +\"iptal\" +\"yetki asimi\"',
                '+\"idarenin takdir yetkisi\" +\"yargisal denetim\" +\"iptal\"',
            ],
        },
        variants: [
            {
                when: /\b(iptal davasi|idari islem|yetki asimi|hukuka aykirilik)\b/i,
                subdomain: 'idare_iptal',
                core: 'Idari islemin yetki, sekil ve sebep yonlerinden hukuka uygunlugu',
                retrieval: ['idari islem iptali', 'yetki asimi', 'hukuka aykirilik'],
                support: ['orantililik', 'hukuki guvenlik', 'takdir yetkisi'],
                sourcePolicy: 'danistay',
                routingMode: 'source_first',
                clauses: [
                    '+\"idari islem\" +\"iptal\" +\"yetki asimi\"',
                    '+\"hukuka aykirilik\" +\"orantililik\" +\"iptal\"',
                ],
            },
            {
                when: /\b(imar para cezasi|ruhsata aykiri yapi|yikim karari|imar plani)\b/i,
                subdomain: 'idare_imar',
                core: 'Imar ve yikim isleminde orantililik ile kazanilmis hak denetimi',
                retrieval: ['imar para cezasi', 'ruhsata aykiri yapi', 'yikim karari'],
                support: ['orantililik', 'imar plani', 'kazanilmis hak'],
                primaryBirimCodes: ['D6'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"imar para cezasi\" +\"orantililik\" +\"iptal\"',
                    '+\"imar plani\" +\"iptal\" +\"kazanilmis hak\"',
                ],
                suggestedCourt: '6. Daire',
            },
            {
                when: /\b(tam yargi|idari eylem|hizmet kusuru)\b/i,
                subdomain: 'idare_tam_yargi',
                core: 'Tam yargi davasinda idarenin sorumlulugu ve tazmin kosullari',
                retrieval: ['tam yargi davasi', 'idari eylem', 'tazminat'],
                support: ['hizmet kusuru', 'kusursuz sorumluluk', 'zarar'],
                sourcePolicy: 'danistay',
                primaryBirimCodes: ['D10'],
                routingMode: 'source_first',
                clauses: [
                    '+\"tam yargi davasi\" +\"idari eylem\" +\"kusur\"',
                    '+\"hizmet kusuru\" +\"tazminat\" +\"idare\"',
                ],
            },
            {
                when: /\b(disiplin cezasi|memurluk|savunma hakki|ihrac)\b/i,
                subdomain: 'idare_disiplin',
                core: 'Disiplin cezasinda savunma hakki ve olcululuk ilkesi',
                retrieval: ['disiplin cezasi', 'savunma hakki', 'iptal'],
                support: ['memurluk', 'ihrac', 'olcululuk'],
                primaryBirimCodes: ['D12'],
                secondaryBirimCodes: ['D2', 'D5'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"disiplin cezasi\" +\"savunma hakki\" +\"iptal\"',
                    '+\"memurluk\" +\"disiplin\" +\"olcululuk\"',
                ],
                suggestedCourt: '12. Daire, 2. Daire, 5. Daire',
            },
            {
                when: /\b(kamu ihale|ihale iptal|4734)\b/i,
                subdomain: 'idare_kamu_ihale',
                core: 'Kamu ihale surecinde usul ve rekabet ilkesine uygunluk',
                retrieval: ['kamu ihale', 'ihale iptal', '4734'],
                support: ['usul', 'rekabet', 'degerlendirme disi'],
                primaryBirimCodes: ['D13'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"ihale iptal\" +\"kamu ihale\" +\"usul\"',
                    '+\"4734\" +\"rekabet\" +\"iptal\"',
                ],
                suggestedCourt: '13. Daire',
            },
        ],
    },
    vergi: {
        label: 'Vergi hukuku',
        profiles: ['idare'],
        sources: ['danistay'],
        suggestedCourt: '3. Daire, 7. Daire, 9. Daire, VDDK',
        strictResultMode: true,
        principles: ['ispat yuku', 'tarhiyat denetimi', 'zamanaasimi'],
        negative: ['ceza dairesi', 'hukuk dairesi', 'bosanma', 'is hukuku'],
        detection: [
            /\b(kdv|vergi ziya|tarhiyat|sahte fatura|kurumlar vergisi|gelir vergisi|mukellef)\b/i,
            /\b(vergi inceleme raporu|gib|tarhiyat ihbarnamesi|ozel usulsuzluk)\b/i,
        ],
        defaultVariant: {
            subdomain: 'vergi_genel',
            core: 'Vergi uyusmazliginda tarhiyat, ceza ve ispat sorunlarinin degerlendirilmesi',
            retrieval: ['vergi tarhiyati', 'vergi ziyai', 'tarhiyat'],
            support: ['ispat yuku', 'inceleme raporu', 'zamanaasimi'],
            sourcePolicy: 'danistay',
            primaryBirimCodes: ['D3', 'D7', 'D9'],
            routingMode: 'source_first',
            clauses: [
                '+\"vergi ziya\" +\"tarhiyat\" +\"ispat yuku\"',
                '+\"resen tarhiyat\" +\"mukellef\" +\"ispat\"',
            ],
        },
        variants: [
            {
                when: /\b(kdv|sahte fatura|indirim reddi)\b/i,
                subdomain: 'vergi_kdv_sahte_fatura',
                core: 'Sahte fatura iddiasina dayali KDV indirimi reddi ve ispat yuku',
                retrieval: ['kdv', 'sahte fatura', 'indirim reddi'],
                support: ['ispat yuku', 'inceleme raporu', 'tarhiyat', 'vergi ziyai cezasi', 'muhteviyati itibariyla yaniltici belge'],
                primaryBirimCodes: ['D3'],
                secondaryBirimCodes: ['VDDK'],
                sourcePolicy: 'danistay',
                routingMode: 'primary_secondary',
                must: ['sahte fatura', 'KDV indirimi', 'vergi ziya'],
                deny: ['gumruk', 'ithalat', 'otv', 'gider vergileri'],
                strictMatchMode: 'must_support',
                suggestedCourt: '3. Daire, Vergi Dava Daireleri Kurulu',
                clauses: [
                    '+\"sahte fatura\" +\"KDV indirimi\" +\"vergi ziya\"',
                    "+\"re'sen tarhiyat\" +\"ispat yuku\" +\"mukellef\"",
                    '+\"vergi inceleme raporu\" +\"sahte belge\" +\"KDV\"',
                ],
            },
            {
                when: /\b(gumruk|ithalat|otv|gider vergileri|ozel tuketim vergisi)\b/i,
                subdomain: 'vergi_gumruk_otv',
                core: 'Gumruk, ithalde vergi ve OTV ihtilaflarinda Danistay kararlarinin degerlendirilmesi',
                retrieval: ['gumruk', 'ithalat', 'otv'],
                support: ['gider vergileri', 'ithalde kdv', 'tarhiyat'],
                primaryBirimCodes: ['D7'],
                secondaryBirimCodes: ['VDDK'],
                sourcePolicy: 'danistay',
                routingMode: 'primary_secondary',
                must: ['gumruk', 'otv'],
                strictMatchMode: 'must_support',
                suggestedCourt: '7. Daire, Vergi Dava Daireleri Kurulu',
                clauses: [
                    '+\"gumruk\" +\"otv\" +\"tarhiyat\"',
                    '+\"ithalat\" +\"kdv\" +\"gumruk\"',
                ],
            },
            {
                when: /\b(vergi ziya|usulsuzluk cezasi|cezali tarhiyat)\b/i,
                subdomain: 'vergi_ceza_tarhiyat',
                core: 'Vergi ziya ve usulsuzluk cezalarinda ceza dayanaklarinin denetimi',
                retrieval: ['vergi ziya cezasi', 'cezali tarhiyat', 'usulsuzluk cezasi'],
                support: ['kast', 'belge', 'ispat yuku'],
                sourcePolicy: 'danistay',
                primaryBirimCodes: ['D3', 'D7', 'D9'],
                routingMode: 'source_first',
                clauses: [
                    '+\"vergi ziya\" +\"kasit\" +\"ceza\"',
                    '+\"ozel usulsuzluk cezasi\" +\"belge\" +\"iptal\"',
                ],
            },
        ],
    },
    tuketici: {
        label: 'Tuketici hukuku',
        profiles: ['hukuk'],
        sources: ['yargitay', 'uyap'],
        suggestedCourt: '3. Hukuk Dairesi',
        strictResultMode: true,
        principles: ['ayip', 'cayma hakki', 'ispat yuku'],
        negative: ['ceza dairesi', 'danistay', 'idare mahkemesi', 'tck'],
        detection: [/\b(tuketici|ayipli mal|ayipli hizmet|hakem heyeti|cayma hakki|tkhk)\b/i],
        defaultVariant: {
            subdomain: 'tuketici_genel',
            core: 'Tuketici uyusmazliginda ayip, iade ve cayma hakkinin degerlendirilmesi',
            retrieval: ['tuketici sozlesmesi', 'ayipli mal', 'tkhk 11'],
            support: ['cayma hakki', 'bedel iadesi', 'hakem heyeti'],
            suggestedCourt: '3. Hukuk Dairesi',
            primaryBirimCodes: ['H3'],
            routingMode: 'hard_primary',
            clauses: [
                '+\"ayipli mal\" +\"TKHK 11\" +\"iade\"',
                '+\"cayma hakki\" +\"bedel iadesi\" +\"tuketici\"',
            ],
        },
        variants: [
            {
                when: /\b(ayipli mal|tkhk 11|bedel iadesi)\b/i,
                subdomain: 'tuketici_ayipli_mal',
                core: 'Ayipli mal nedeniyle bedel iadesi veya degisim hakkina iliskin uyusmazlik',
                retrieval: ['tuketici sozlesmesi', 'ayipli mal', 'tkhk 11'],
                support: ['bedel iadesi', 'degisim', 'garanti'],
                suggestedCourt: '3. Hukuk Dairesi',
                primaryBirimCodes: ['H3'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"ayipli mal\" +\"TKHK 11\" +\"iade\"',
                    '+\"ayipli mal\" +\"garanti\" +\"degisim\"',
                ],
            },
            {
                when: /\b(cayma hakki|mesafeli sozlesme)\b/i,
                subdomain: 'tuketici_cayma',
                core: 'Mesafeli sozlesmede cayma hakkinin kullanimi ve iade kosullari',
                retrieval: ['cayma hakki', 'mesafeli sozlesme', 'bedel iadesi'],
                support: ['sure', 'iade', 'hakem heyeti'],
                suggestedCourt: '3. Hukuk Dairesi',
                primaryBirimCodes: ['H3'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"cayma hakki\" +\"mesafeli sozlesme\" +\"iade\"',
                    '+\"cayma hakki\" +\"bedel iadesi\" +\"tuketici\"',
                ],
            },
            {
                when: /\b(tuketici kredisi|kredi karti|finansman|dosya masrafi|faiz iadesi)\b/i,
                subdomain: 'tuketici_kredi_finansman',
                core: 'Tuketici kredisi ve finansman iliskisinde faiz, masraf ve iade talepleri',
                retrieval: ['tuketici kredisi', 'kredi karti', 'finansman'],
                support: ['faiz', 'dosya masrafi', 'bedel iadesi'],
                suggestedCourt: '3. Hukuk Dairesi, 11. Hukuk Dairesi',
                primaryBirimCodes: ['H3'],
                secondaryBirimCodes: ['H11'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"tuketici kredisi\" +\"faiz\" +\"iade\"',
                    '+\"kredi karti\" +\"dosya masrafi\" +\"tuketici\"',
                ],
            },
        ],
    },
    sigorta: {
        label: 'Sigorta hukuku',
        profiles: ['hukuk'],
        sources: ['yargitay'],
        suggestedCourt: '4. Hukuk Dairesi, 11. Hukuk Dairesi',
        strictResultMode: true,
        principles: ['rizikonun gerceklesmesi', 'kusur', 'rucu'],
        negative: ['ceza dairesi', 'danistay', 'bosanma'],
        detection: [/\b(sigorta|kasko|trafik kazasi|deger kaybi|riziko|police|rucu|rucuen)\b/i],
        defaultVariant: {
            subdomain: 'sigorta_genel',
            core: 'Sigorta iliskisinde police kapsami ve tazminat sorumlulugu',
            retrieval: ['sigorta sozlesmesi', 'tazminat', 'rizikonun gerceklesmesi'],
            support: ['rucu', 'kusur', 'hasar'],
            suggestedCourt: '4. Hukuk Dairesi, 11. Hukuk Dairesi',
            primaryBirimCodes: ['H4'],
            secondaryBirimCodes: ['H11'],
            routingMode: 'primary_secondary',
            clauses: [
                '+\"sigorta\" +\"rizikonun gerceklesmesi\" +\"tazminat\"',
                '+\"sigorta\" +\"rucu\" +\"sorumluluk\"',
            ],
        },
        variants: [
            {
                when: /\b(deger kaybi|trafik kazasi)\b/i,
                subdomain: 'sigorta_deger_kaybi',
                core: 'Trafik kazasinda deger kaybi ve sigorta sorumlulugu',
                retrieval: ['deger kaybi', 'trafik kazasi', 'sigorta tazminati'],
                support: ['kusur', 'ekspertiz', 'hasar'],
                suggestedCourt: '4. Hukuk Dairesi, 11. Hukuk Dairesi',
                primaryBirimCodes: ['H4'],
                secondaryBirimCodes: ['H11'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"deger kaybi\" +\"trafik kazasi\" +\"tazminat\"',
                    '+\"sigorta\" +\"trafik kazasi\" +\"kusur\"',
                ],
            },
            {
                when: /\b(rucu|rucuen)\b/i,
                subdomain: 'sigorta_rucu',
                core: 'Sigorta sirketinin rucu talebinde kusur ve police kapsami',
                retrieval: ['sigorta', 'rucu', 'sorumluluk'],
                support: ['kusur', 'police', 'odeme'],
                suggestedCourt: '4. Hukuk Dairesi, 11. Hukuk Dairesi',
                primaryBirimCodes: ['H4'],
                secondaryBirimCodes: ['H11'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"sigorta\" +\"rucu\" +\"sorumluluk\"',
                    '+\"rucuen\" +\"kusur\" +\"sigorta\"',
                ],
            },
            {
                when: /\b(deniz sigortasi|nakliyat sigortasi|tasima sigortasi|prim alacagi|reasurans)\b/i,
                subdomain: 'sigorta_ticari',
                core: 'Ticari sigorta iliskisinde prim, teminat ve tasima-deniz rizikolarinin degerlendirilmesi',
                retrieval: ['deniz sigortasi', 'nakliyat sigortasi', 'prim alacagi'],
                support: ['reasurans', 'teminat', 'tasima'],
                suggestedCourt: '11. Hukuk Dairesi',
                primaryBirimCodes: ['H11'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"deniz sigortasi\" +\"teminat\" +\"riziko\"',
                    '+\"nakliyat sigortasi\" +\"prim alacagi\" +\"sigorta\"',
                ],
            },
        ],
    },
    miras: {
        label: 'Miras hukuku',
        profiles: ['hukuk'],
        sources: ['yargitay'],
        suggestedCourt: '7. Hukuk Dairesi, 1. Hukuk Dairesi',
        strictResultMode: true,
        principles: ['sakli pay', 'muris muvazaasi', 'tenkis'],
        negative: ['ceza dairesi', 'danistay', 'is hukuku'],
        detection: [/\b(miras|tenkis|muris muvazaasi|vasiyetname|sakli pay|mirasin reddi)\b/i],
        defaultVariant: {
            subdomain: 'miras_genel',
            core: 'Miras hukukunda tasarruf sinirlari ve mirascilik uyusmazliklari',
            retrieval: ['miras', 'tenkis', 'mirascilik'],
            support: ['sakli pay', 'vasiyetname', 'tasfiye'],
            suggestedCourt: '7. Hukuk Dairesi',
            primaryBirimCodes: ['H7'],
            routingMode: 'hard_primary',
            clauses: [
                '+\"tenkis\" +\"sakli pay\" +\"TMK 560\"',
                '+\"vasiyetname\" +\"iptal\" +\"miras\"',
            ],
        },
        variants: [
            {
                when: /\b(muris muvazaasi|tapu iptali)\b/i,
                subdomain: 'miras_muris_muvazaasi',
                core: 'Muris muvazaasi nedeniyle tapu iptali ve tescil istemi',
                retrieval: ['muris muvazaasi', 'tapu iptali', 'miras'],
                support: ['mirascilik', 'sakli pay', 'tescil'],
                suggestedCourt: '1. Hukuk Dairesi, 7. Hukuk Dairesi',
                primaryBirimCodes: ['H1'],
                secondaryBirimCodes: ['H7'],
                routingMode: 'primary_secondary',
                clauses: [
                    '+\"muris muvazaasi\" +\"tapu iptali\" +\"tescil\"',
                    '+\"muris muvazaasi\" +\"miras\" +\"tescil\"',
                ],
            },
            {
                when: /\b(tenkis|sakli pay|tmk 560)\b/i,
                subdomain: 'miras_tenkis',
                core: 'Sakli payin ihlali halinde tenkis talebinin kosullari',
                retrieval: ['tenkis', 'sakli pay', 'tmk 560'],
                support: ['mirasci', 'bagis', 'tasarruf orani'],
                suggestedCourt: '7. Hukuk Dairesi',
                primaryBirimCodes: ['H7'],
                routingMode: 'hard_primary',
                clauses: [
                    '+\"tenkis\" +\"sakli pay\" +\"TMK 560\"',
                    '+\"sakli pay\" +\"mirasci\" +\"tenkis\"',
                ],
            },
        ],
    },
    anayasa: {
        label: 'Anayasa hukuku',
        profiles: ['anayasa'],
        sources: ['anayasa'],
        suggestedCourt: 'Anayasa Mahkemesi',
        strictResultMode: true,
        principles: ['ihlal', 'orantililik', 'etkili basvuru'],
        negative: ['ceza dairesi', 'hukuk dairesi', 'danistay'],
        detection: [
            /\b(anayasa mahkemesi|aym|bireysel basvuru|anayasa 36|anayasa 26|anayasa 35|aihs)\b/i,
            /\b(anayasaya aykirilik|norm denetimi|kanun iptali|olcululuk|belirlilik)\b/i,
        ],
        defaultVariant: {
            subdomain: 'anayasa_bireysel_basvuru',
            decisionType: 'bireysel_basvuru',
            core: 'Anayasal hak ihlali iddiasinda bireysel basvuru sartlari ve ihlal denetimi',
            retrieval: ['bireysel basvuru', 'ihlal', 'anayasa mahkemesi'],
            support: ['etkili basvuru', 'orantililik', 'yeniden yargilama'],
            sourcePolicy: 'anayasa',
            routingMode: 'source_first',
            must: ['bireysel basvuru', 'hak ihlali'],
            deny: ['yargitay', 'danistay', 'hukuk dairesi', 'ceza dairesi'],
            strictMatchMode: 'must_support',
            clauses: [
                '+\"adil yargilanma\" +\"silahlarin esitligi\" +\"ihlal\"',
                '+\"makul sure\" +\"yargilama\" +\"tazminat\"',
            ],
            negative: ['norm denetimi', 'kanun iptali', 'iptal davasi'],
        },
        variants: [
            {
                when: /\b(makul sure|makul surede yargilanma|yargilamanin uzun surmesi)\b/i,
                subdomain: 'anayasa_bireysel_basvuru_makul_sure',
                decisionType: 'bireysel_basvuru',
                core: 'Anayasa Mahkemesi bireysel basvurusunda makul surede yargilanma hakkinin ihlali ve tazminat denetimi',
                retrieval: ['bireysel basvuru', 'makul sure', 'hak ihlali'],
                support: ['anayasa mahkemesi', 'adil yargilanma hakki', 'manevi tazminat', 'yeniden yargilama'],
                sourcePolicy: 'anayasa',
                routingMode: 'source_first',
                must: ['makul sure'],
                deny: ['yargitay', 'danistay', 'hukuk dairesi', 'ceza dairesi'],
                strictMatchMode: 'must_support',
                clauses: [
                    '+\"bireysel basvuru\" +\"makul sure\" +\"hak ihlali\"',
                    '+\"makul surede yargilanma\" +\"manevi tazminat\" +\"ihlal\"',
                ],
                negative: ['norm denetimi', 'kanun iptali', 'iptal davasi'],
            },
            {
                when: /\b(bireysel basvuru|aym|adil yargilanma|ifade ozgurlugu|mulkiyet hakki|anayasa 36|anayasa 26|anayasa 35|makul sure|etkili basvuru|aihs)\b/i,
                subdomain: 'anayasa_bireysel_basvuru',
                decisionType: 'bireysel_basvuru',
                core: 'Anayasa Mahkemesi bireysel basvurusunda temel hak ihlali ve orantililik denetimi',
                retrieval: ['bireysel basvuru', 'ihlal', 'anayasa mahkemesi'],
                support: ['adil yargilanma hakki', 'etkili basvuru', 'orantililik', 'yeniden yargilama'],
                sourcePolicy: 'anayasa',
                routingMode: 'source_first',
                must: ['bireysel basvuru', 'hak ihlali'],
                deny: ['yargitay', 'danistay', 'hukuk dairesi', 'ceza dairesi'],
                strictMatchMode: 'must_support',
                clauses: [
                    '+\"adil yargilanma\" +\"silahlarin esitligi\" +\"ihlal\"',
                    '+\"ifade ozgurlugu\" +\"basin ozgurlugu\" +\"ihlal\"',
                    '+\"makul sure\" +\"yargilama\" +\"tazminat\"',
                    '+\"etkili basvuru\" +\"ic hukuk yolu\" +\"tuketme\"',
                ],
                negative: ['norm denetimi', 'kanun iptali', 'iptal davasi'],
            },
            {
                when: /\b(anayasaya aykirilik|kanun iptali|iptal davasi|norm denetimi|belirlilik ilkesi|olcululuk)\b/i,
                subdomain: 'anayasa_norm_denetimi',
                decisionType: 'norm_denetimi',
                core: 'Norm denetiminde kanun veya KHK hukumlerinin Anayasaya uygunlugunun degerlendirilmesi',
                retrieval: ['anayasaya aykirilik', 'kanun iptali', 'norm denetimi'],
                support: ['hukuk devleti', 'belirlilik ilkesi', 'olcululuk', 'esitlik ilkesi'],
                sourcePolicy: 'anayasa',
                routingMode: 'source_first',
                must: ['anayasaya aykirilik', 'norm denetimi'],
                deny: ['yargitay', 'danistay', 'hukuk dairesi', 'ceza dairesi'],
                strictMatchMode: 'must_support',
                clauses: [
                    '+\"anayasaya aykirilik\" +\"kanun\" +\"iptal\"',
                    '+\"hukuk devleti\" +\"belirlilik ilkesi\" +\"iptal\"',
                    '+\"temel hak sinirlamasi\" +\"orantililik\" +\"olcululuk\"',
                ],
                negative: ['bireysel basvuru', 'ihlal', 'yeniden yargilama'],
            },
        ],
    },
};

export const DOMAIN_PRIORITY = [
    'anayasa',
    'vergi',
    'idare',
    'ceza',
    'aile',
    'icra',
    'is_hukuku',
    'sigorta',
    'tuketici',
    'miras',
    'ticaret',
    'gayrimenkul',
    'borclar',
];

const mergeUnique = (...lists) => [...new Set(lists.flat().filter(Boolean))];

const prependVariants = (domainKey, variants) => {
    const domain = DOMAIN_RULES[domainKey];
    if (!domain) return;
    if (!Array.isArray(domain.variants)) {
        domain.variants = [];
    }
    domain.variants.unshift(...variants);
};

const patchVariant = (domainKey, subdomain, patch = {}) => {
    const domain = DOMAIN_RULES[domainKey];
    const variant = Array.isArray(domain?.variants)
        ? domain.variants.find((item) => item?.subdomain === subdomain)
        : null;

    if (!variant) return;

    if (patch.retrieval) variant.retrieval = mergeUnique(variant.retrieval, patch.retrieval);
    if (patch.support) variant.support = mergeUnique(variant.support, patch.support);
    if (patch.evidence) variant.evidence = mergeUnique(variant.evidence, patch.evidence);
    if (patch.clauses) variant.clauses = mergeUnique(variant.clauses, patch.clauses);
    if (patch.must) variant.must = mergeUnique(variant.must, patch.must);
    if (patch.deny) variant.deny = mergeUnique(variant.deny, patch.deny);
    if (patch.negative) variant.negative = mergeUnique(variant.negative, patch.negative);
};

prependVariants('icra', [
    {
        when: /\b(ihalenin feshi|ihale feshi|kiymet takdiri|satis ilani|ihale bedeli)\b/i,
        subdomain: 'icra_ihalenin_feshi',
        suggestedCourt: '12. Hukuk Dairesi',
        primaryBirimCodes: ['H12'],
        secondaryBirimCodes: ['H3'],
        routingMode: 'primary_secondary',
        core: 'Icra satis ihalesinin feshinde satis ilaninin, artirma usulunun ve kiymet takdirinin denetlenmesi',
        must: ['ihalenin feshi', 'kiymet takdiri'],
        retrieval: ['ihalenin feshi', 'ihale feshi', 'kiymet takdiri'],
        support: ['satis ilani', 'artirma', 'ihale bedeli', 'usulsuzluk'],
        clauses: [
            '+\"ihalenin feshi\" +\"ihale\" +\"kiymet takdiri\"',
            '+\"satis ilani\" +\"ihale feshi\" +\"usulsuzluk\"',
        ],
    },
    {
        when: /\b(meskeniyet|haline munasip ev|evin haczedilmezligi|haline munasip konut)\b/i,
        subdomain: 'icra_meskeniyet',
        suggestedCourt: '12. Hukuk Dairesi',
        primaryBirimCodes: ['H12'],
        routingMode: 'hard_primary',
        core: 'Meskeniyet iddiasina dayali haczedilemezlik sikayetinde konutun haline munasip olup olmadigi',
        must: ['meskeniyet', 'haczedilemezlik'],
        retrieval: ['meskeniyet', 'haczedilemezlik', 'haline munasip ev'],
        support: ['konut', 'haciz', 'icra mahkemesi'],
        clauses: [
            '+\"meskeniyet\" +\"haczedilemezlik\" +\"haline munasip ev\"',
            '+\"haczedilemezlik\" +\"konut\" +\"icra mahkemesi\"',
        ],
    },
    {
        when: /\b(menfi tespit|icra inkar tazminati|takibin iptali|borcun bulunmadigi)\b/i,
        subdomain: 'icra_menfi_tespit',
        suggestedCourt: '11. Hukuk Dairesi',
        primaryBirimCodes: ['H11'],
        secondaryBirimCodes: ['H12'],
        routingMode: 'primary_secondary',
        core: 'Menfi tespit davasinda borcun bulunup bulunmadigi ve icra inkar tazminati kosullari',
        must: ['menfi tespit', 'IIK 72'],
        retrieval: ['menfi tespit', 'IIK 72', 'icra inkar tazminati'],
        support: ['takibin durdurulmasi', 'borcun bulunmadigi', 'itiraz'],
        clauses: [
            '+\"menfi tespit\" +\"IIK 72\" +\"icra inkar tazminati\"',
            '+\"borcun bulunmadigi\" +\"takibin durdurulmasi\" +\"menfi tespit\"',
        ],
    },
]);

patchVariant('icra', 'icra_ticari_itirazin_iptali', {
    must: ['IIK 67', 'itirazin iptali'],
    retrieval: ['itirazin iptali', 'IIK 67', 'ticari defter'],
    support: ['cari hesap', 'fatura', 'mutabakat', 'icra inkar tazminati'],
    clauses: [
        '+\"cari hesap\" +\"itirazin iptali\" +\"IIK 67\"',
        '+\"ticari defter\" +\"fatura\" +\"icra inkar tazminati\"',
        'itirazin iptali cari hesap alacagi icra inkar tazminati',
        'menfi tespit istirdat icra takibi',
        'IIK 67 itirazin iptali',
    ],
});

patchVariant('icra', 'icra_haciz', {
    clauses: [
        'haczedilmezlik sikayeti meskeniyet',
        'icra mahkemesi haciz karari',
        'ihalenin feshi satis ilani kiymet takdiri',
        'IIK 82 meskeniyet iddiasi',
    ],
});

patchVariant('is_hukuku', 'is_hukuku_fazla_mesai', {
    must: ['fazla mesai', 'puantaj'],
    retrieval: ['fazla mesai', 'fazla calisma', 'puantaj'],
    support: ['bordro', 'ucret hesap pusulasi', 'devam cizelgesi', 'serbest zaman'],
});

patchVariant('borclar', 'borclar_kira', {
    must: ['TBK 350', 'ihtiyac nedeniyle tahliye'],
    retrieval: ['ihtiyac nedeniyle tahliye', 'TBK 350', 'samimi ihtiyac'],
    support: ['konut ihtiyaci', 'is yeri ihtiyaci', 'kiralananin tahliyesi', 'gereksinim'],
});

patchVariant('ceza', 'ceza_uyusturucu', {
    must: ['TCK 188', 'TCK 191'],
});

prependVariants('is_hukuku', [
    {
        when: /\b(270 saat|270 saati|yillik 270 saat|fazla calisma 270)\b/i,
        subdomain: 'is_hukuku_fazla_calisma_270_saat',
        suggestedCourt: '9. Hukuk Dairesi',
        primaryBirimCodes: ['H9'],
        routingMode: 'hard_primary',
        core: 'Fazla calismada 270 saat uzeri iddianin bordro ve puantajla degerlendirilmesi',
        must: ['270 saat', 'fazla calisma'],
        retrieval: ['fazla calisma', '270 saat', 'bordro'],
        support: ['puantaj', 'ucret hesap pusulasi', 'devam cizelgesi', 'ispat'],
        evidence: ['bordro', 'puantaj kaydi', 'ucret hesap pusulasi', 'devam cizelgesi'],
        clauses: [
            '+\"270 saat\" +\"fazla calisma\" +\"puantaj\"',
            '+\"bordro\" +\"fazla calisma\" +\"ucret hesap pusulasi\"',
        ],
    },
    {
        when: /\b(fazla mesai|puantaj|bordro|ucret hesap pusulasi|ise giris cikis kayitlari)\b/i,
        subdomain: 'is_hukuku_fazla_mesai_puantaj',
        suggestedCourt: '9. Hukuk Dairesi',
        primaryBirimCodes: ['H9'],
        routingMode: 'hard_primary',
        core: 'Fazla mesai alacaginda puantaj, bordro ve elektronik kayitlarla ispatin degerlendirilmesi',
        must: ['fazla mesai', 'puantaj'],
        retrieval: ['fazla mesai', 'fazla calisma', 'puantaj'],
        support: ['bordro', 'ucret hesap pusulasi', 'devam cizelgesi', 'serbest zaman'],
        evidence: ['bordro', 'puantaj kaydi', 'ucret hesap pusulasi', 'devam cizelgesi', 'ise giris cikis kayitlari'],
        clauses: [
            '+\"fazla mesai\" +\"puantaj\" +\"ispat\"',
            '+\"fazla calisma\" +\"bordro\" +\"ucret hesap pusulasi\"',
        ],
    },
    {
        when: /\b(hizmet tespiti|sigortalilik tespiti|5510|prim bildirimi|sgk kayitlari?)\b/i,
        subdomain: 'is_hukuku_hizmet_tespiti_sgk',
        suggestedCourt: '10. Hukuk Dairesi',
        primaryBirimCodes: ['H10'],
        routingMode: 'hard_primary',
        core: 'Hizmet tespitinde calisma olgusu, SGK kayitlari ve prim bildiriminin degerlendirilmesi',
        must: ['hizmet tespiti', 'sigortalilik tespiti'],
        retrieval: ['hizmet tespiti', 'sigortalilik tespiti', 'sgk'],
        support: ['5510', 'prim bildirimi', 'calisma olgusu', 'tanik'],
        clauses: [
            '+\"hizmet tespiti\" +\"sgk\" +\"sigortalilik\"',
            '+\"5510\" +\"sigortalilik tespiti\" +\"calisma olgusu\"',
        ],
    },
    {
        when: /\b(is kazasi|meslek hastaligi|rucu|rucuen)\b/i,
        subdomain: 'is_hukuku_is_kazasi_rucu',
        suggestedCourt: '10. Hukuk Dairesi',
        primaryBirimCodes: ['H10'],
        routingMode: 'hard_primary',
        core: 'Is kazasi ve meslek hastaliginda kusur ile SGK rucu iliskisinin degerlendirilmesi',
        must: ['is kazasi', 'rucu'],
        retrieval: ['is kazasi', 'meslek hastaligi', 'rucu'],
        support: ['sgk geliri', 'kusur', 'surekli is goremezlik'],
        clauses: [
            '+\"is kazasi\" +\"sgk\" +\"kusur\"',
            '+\"meslek hastaligi\" +\"rucu\" +\"surekli is goremezlik\"',
        ],
    },
]);

prependVariants('ceza', [
    {
        when: /\b(kisisel kullanim siniri|kullanici tanik|sadece kullanim|beraat)\b/i,
        subdomain: 'ceza_uyusturucu_kullanma_savunmasi',
        suggestedCourt: '10. Ceza Dairesi',
        primaryBirimCodes: ['C10'],
        secondaryBirimCodes: ['C8', 'C20'],
        routingMode: 'primary_secondary',
        core: 'Uyusturucu dosyasinda kullanmak icin bulundurma savunmasi ile ticaret kastinin ayrilmasi',
        must: ['kullanmak icin bulundurma', 'TCK 191'],
        retrieval: ['kullanmak icin bulundurma', 'TCK 191', 'kisisel kullanim siniri'],
        support: ['ticaret kasti', 'kullanici tanik', 'beraat', 'sadece kullanim'],
        evidence: ['paketleme', 'hassas terazi', 'hts kaydi', 'telefon incelemesi', 'tanik'],
        clauses: [
            '+\"kullanmak icin bulundurma\" +\"kisisel kullanim siniri\" +\"TCK 191\"',
            '+\"kullanmak icin bulundurma\" +\"kisisel kullanim siniri\" +\"beraat\"',
            '+\"ticaret kasti\" +\"kullanici tanik\" +\"beraat\"',
        ],
    },
    {
        when: /^(?=.*\bpaketleme\b)(?=.*\b(?:hassas terazi|ele gecirilen miktar)\b).*$/i,
        subdomain: 'ceza_uyusturucu_paketleme',
        suggestedCourt: '10. Ceza Dairesi',
        primaryBirimCodes: ['C10'],
        secondaryBirimCodes: ['C8', 'C20'],
        routingMode: 'primary_secondary',
        core: 'Uyusturucu madde dosyasinda paketleme, hassas terazi ve miktar delillerinden ticaret kastinin degerlendirilmesi',
        must: ['paketleme', 'TCK 188'],
        retrieval: ['paketleme', 'hassas terazi', 'TCK 188'],
        support: ['ele gecirilen miktar', 'hts', 'telefon incelemesi', 'tanik', 'ticaret kasti'],
        evidence: ['paketleme', 'hassas terazi', 'hts kaydi', 'telefon incelemesi', 'ele gecirilen miktar'],
        clauses: [
            '+\"paketleme\" +\"hassas terazi\" +\"TCK 188\"',
            '+\"ele gecirilen miktar\" +\"ticaret kasti\" +\"uyusturucu\"',
        ],
    },
]);

prependVariants('borclar', [
    {
        when: /\b(TBK 350|ihtiyac nedeniyle tahliye|gereksinim nedeniyle tahliye|konut ihtiyaci|is yeri ihtiyaci)\b/i,
        subdomain: 'borclar_kira_ihtiyac',
        suggestedCourt: '3. Hukuk Dairesi',
        primaryBirimCodes: ['H3'],
        secondaryBirimCodes: ['H12'],
        routingMode: 'primary_secondary',
        core: 'Kiralananin ihtiyac nedeniyle tahliyesinde samimi gereksinim ve TBK 350 kosullarinin degerlendirilmesi',
        must: ['TBK 350', 'ihtiyac nedeniyle tahliye'],
        retrieval: ['ihtiyac nedeniyle tahliye', 'TBK 350', 'samimi ihtiyac'],
        support: ['konut ihtiyaci', 'is yeri ihtiyaci', 'kiralananin tahliyesi', 'gereksinim'],
        clauses: [
            '+\"ihtiyac nedeniyle tahliye\" +\"TBK 350\" +\"samimi ihtiyac\"',
            '+\"konut ihtiyaci\" +\"tahliye\" +\"kiralananin tahliyesi\"',
        ],
    },
    {
        when: /\b(arsa payi karsiligi insaat|yuklenici|eksik imalat|gecikme tazminati)\b/i,
        subdomain: 'borclar_arsa_payi_karsiligi_insaat',
        suggestedCourt: '3. Hukuk Dairesi, 15. Hukuk Dairesi',
        primaryBirimCodes: ['H3'],
        secondaryBirimCodes: ['H15'],
        routingMode: 'primary_secondary',
        core: 'Arsa payi karsiligi insaat sozlesmesinden dogan yuklenici, teslim ve bagimsiz bolum uyusmazligi',
        must: ['arsa payi karsiligi insaat', 'yuklenici'],
        retrieval: ['arsa payi karsiligi insaat', 'yuklenici', 'bagimsiz bolum'],
        support: ['eksik imalat', 'gecikme tazminati', 'teslim', 'sozlesme'],
        clauses: [
            '+\"arsa payi karsiligi insaat\" +\"yuklenici\" +\"bagimsiz bolum\"',
            '+\"eksik imalat\" +\"gecikme tazminati\" +\"teslim\"',
        ],
    },
]);

patchVariant('ceza', 'ceza_uyusturucu', {
    retrieval: ['TCK 188', 'TCK 191', 'uyusturucu madde ticareti'],
    support: ['ticaret kasti', 'kisisel kullanim siniri', 'kullanmak icin bulundurma'],
    evidence: ['paketleme', 'hassas terazi', 'hts kaydi', 'telefon incelemesi'],
});
